/**
 * 6 test policy records for the apex_gear_policies index.
 * Covers layers 1-4 plus one red herring (expired holiday policy).
 */
export const testRecords = [
  {
    objectID: "ret-general-001",
    policy_id: "return-general",
    policy_name: "General Return Policy",
    clause_id: "RET-1.1",
    clause_title: "Standard Return Window",
    text: "All products purchased from Apex Gear may be returned within 30 calendar days of the original purchase date for a full refund, provided the item is in its original condition with all tags and packaging intact. After 30 days, returns will not be accepted unless covered by a specific warranty or exception policy.",
    policy_type: "return",
    policy_layer: 1,
    applies_to: "all",
    product_tags: [],
    conditions: ["within_30_days", "original_condition"],
    effect: "return_approved",
    priority: 10,
    specificity_score: 10,
    effective_date: 1704067200, // 2024-01-01
    expiry_date: null
  },
  {
    objectID: "war-electronics-001",
    policy_id: "warranty-electronics",
    policy_name: "Electronics Category Warranty",
    clause_id: "WAR-2.1",
    clause_title: "Electronics 1-Year Manufacturer Warranty",
    text: "All electronics sold by Apex Gear are covered by a 1-year manufacturer warranty from the date of purchase. This warranty covers defects in materials and workmanship under normal use. Physical damage, water damage, and unauthorized modifications void this warranty.",
    policy_type: "warranty",
    policy_layer: 2,
    applies_to: "electronics",
    product_tags: ["electronics"],
    conditions: ["within_1_year", "manufacturing_defect"],
    effect: "warranty_approved",
    priority: 30,
    specificity_score: 30,
    effective_date: 1704067200,
    expiry_date: null
  },
  {
    objectID: "war-treadmill-001",
    policy_id: "warranty-pro-treadmill",
    policy_name: "Pro-Treadmill X500 Motor Warranty",
    clause_id: "WAR-3.1",
    clause_title: "2-Year Motor Warranty",
    text: "The Pro-Treadmill X500 motor is covered by a dedicated 2-year warranty from the date of purchase. If the motor fails or malfunctions due to manufacturing defects or normal wear during this period, Apex Gear will repair or replace the motor at no cost. This warranty specifically covers: motor failure, unusual motor noise, motor overheating, and belt drive motor issues. This product-specific warranty overrides the general return window for motor-related mechanical defects. Clause 14.b: For motor defects reported within the 2-year warranty period, customers are entitled to a full repair or replacement regardless of whether the 30-day general return window has elapsed.",
    policy_type: "warranty",
    policy_layer: 3,
    applies_to: "Pro-Treadmill X500",
    product_tags: ["fitness", "treadmills"],
    conditions: ["within_2_years", "motor_defect"],
    effect: "warranty_approved",
    priority: 70,
    specificity_score: 80,
    effective_date: 1704067200,
    expiry_date: null
  },
  {
    objectID: "hyg-audio-001",
    policy_id: "hygiene-exception",
    policy_name: "Hygiene Exception Policy",
    clause_id: "HYG-4.1",
    clause_title: "In-Ear Audio Products Hygiene Override",
    text: "For health and hygiene reasons, all in-ear audio products (earbuds, in-ear monitors, custom ear tips) cannot be returned once the sealed packaging has been opened. This policy overrides the standard 30-day return window. Opened in-ear audio products are final sale. Customers may be offered an exchange for the same product if a manufacturing defect is confirmed, but refunds are not available for opened in-ear products regardless of the return window status.",
    policy_type: "hygiene",
    policy_layer: 4,
    applies_to: "in-ear audio",
    product_tags: ["audio", "earbuds", "in-ear"],
    conditions: ["item_opened", "in_ear_audio"],
    effect: "return_denied",
    priority: 90,
    specificity_score: 90,
    effective_date: 1704067200,
    expiry_date: null
  },
  {
    objectID: "dmg-shipping-001",
    policy_id: "shipping-damage",
    policy_name: "Shipping Damage Override Policy",
    clause_id: "DMG-4.1",
    clause_title: "Shipping Damage Claim Override",
    text: "If a product arrives damaged due to shipping, the standard return window is overridden. Customers who report shipping damage to the carrier within 48 hours of delivery are eligible for a full replacement or refund regardless of how much time has passed since the original purchase date. Required: customer must have documented the damage with the shipping carrier within 48 hours of delivery. This policy takes precedence over the general 30-day return window when shipping damage conditions are met.",
    policy_type: "shipping",
    policy_layer: 4,
    applies_to: "all",
    product_tags: [],
    conditions: ["shipping_damage", "carrier_report_48h"],
    effect: "return_approved",
    priority: 85,
    specificity_score: 85,
    effective_date: 1704067200,
    expiry_date: null
  },
  {
    objectID: "hol-special-001",
    policy_id: "holiday-special",
    policy_name: "Holiday Season Extended Return Policy",
    clause_id: "HOL-1.1",
    clause_title: "Holiday Extended Return Window",
    text: "Purchases made between November 15, 2024 and December 31, 2024 are eligible for an extended 60-day return window. All other standard return conditions apply. This extension applies only to purchases made during the specified holiday period.",
    policy_type: "return",
    policy_layer: 1,
    applies_to: "all",
    product_tags: [],
    conditions: ["purchased_holiday_2024"],
    effect: "return_approved",
    priority: 15,
    specificity_score: 15,
    effective_date: 1731628800, // 2024-11-15
    expiry_date: 1740787200    // 2025-02-28 (expired)
  }
];
